### PR TITLE
Backward compatibility for upgrading from 3.0.x

### LINKED ISSUE #29: Breaking change from 3.0.x to 3.4
In v3.4 you introduced the dkim.mailers config value, which is now a mandatory. 

If someone simply upgrades from 3.0.x to 3.4.x this config parameter is missing, and sending mails fails. So you created a breaking change, when only increasing the minor version. According to Semantic Versioning backward incompatible changes should be marked by increasing the major version number.

Sadly, this issue broke my booking system for a few days, because wie relied to version ^3.0 in our composer.json, which lead to a silent upgrade to v3.4.1.

I will provide a patch, that makes version 3.4 backward compatible again. The other option would be to deleted v3.4 and increase it's version number to 4.0.

Thanks for all your work!

### PR DESCRIPTION
**Pull request by poepperl-cc**
Closes #29

### CODE REVIEW

File: src/Mailer.php [hunk 1]
```diff
@@ -35,7 +35,7 @@ public function send($view, array $data = [], $callback = null)
         // Once we have retrieved the view content for the e-mail we will set the body
         // of this message using the HTML type, which will provide a simple wrapper
         // to creating view based emails that are able to receive arrays of data.
-        if (! is_null($callback)) {
+        if (!is_null($callback)) {
```
Comment (simonschaufi) [inline src/Mailer.php:38]: Please no code style changes together with bugfixes.

Comment (poepperl-cc) [reply src/Mailer.php:38]: Sorry, how should we continue? (It's my first pull-request ...)

Comment (simonschaufi) [reply src/Mailer.php:38]: Simply revert the change, amend the change and force push again.

**Comment by simonschaufi** [comment]
Please squash and rebase the commits locally as the branch can't be merged right now
